### ISSUE TITLE
PHP Warning when [url][/url] BBCode is empty

### ISSUE THREAD

**Issue by tomS3210** [primehalo/primelinks#2]
Hello,

Thanks a lot for you exetension, i'm using it on my site www.forumgolf7.fr/forum and i have this issue. I know [url][/url] is not supposed to be empty but sometimes it is and then we have this error on the top of the forum page.

**PHP Warning when [url][/url] BBCode is empty :** 

[phpBB Debug] PHP Warning: in file [ROOT]/ext/primehalo/primelinks/event/main_listener.php on line 487: strpos(): Empty needle

[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4628: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3365)

[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4628: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3365)

[phpBB Debug] PHP Warning: in file [ROOT]/includes/functions.php on line 4628: Cannot modify header information - headers already sent by (output started at [ROOT]/includes/functions.php:3365)

Thanks for your help :-)

Regards
Thomas

**Comment by primehalo** [comment]
Thanks for the report. I have updated with a fix.

**Comment by tomS3210** [comment]
Hello,

1.1.6 installed and it is working, you are so fast, thanks a lot !

Have a good day

Regards

Thomas
